name: cd-azure

on:
  push:
    paths:
      - ".github/workflows/cd-azure.yml"
      - "api/**"
  workflow_dispatch: # manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # all commits, so we can generate version off of tags/commit sha...
      - uses: docker/setup-buildx-action@v3
      - run: docker buildx ls
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - run: ./build-push.sh # can reuse local build scripts for CI/CD
        working-directory: api
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy.outputs.webapp-url }}
    needs: build
    steps:
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/webapps-deploy@v3
        id: deploy
        with:
          app-name: gh-actions-web-api
          images: weshigbee/actions-web:latest
          resource-group-name: gh-actions
