name: upper-image

on:
  push:
    paths:
      - ".github/workflows/upper-image.yml"
      - "upper/**"
  workflow_dispatch: # manual

permissions:
  packages: write
  contents: read # not needed in public repos

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker version
      - run: docker image build -t upper .
        working-directory: ./upper
      - name: test it
        run: docker container run upper hello wes
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }} # g0t4
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker tag upper ghcr.io/g0t4/upper:latest
      - run: docker tag upper ghcr.io/g0t4/upper:${{ github.ref_name }}
      - run: docker push ghcr.io/g0t4/upper:latest
      - run: docker push ghcr.io/g0t4/upper:${{ github.ref_name }}

