name: Artifacts
on:
  push:

defaults:
  run:
    working-directory: upper
jobs:
  capture:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.x'
      - run: ls
      - run: go build
      - run: ls
      - run: go test -v
      - uses: actions/upload-artifact@v4
        with:
          path: "./upper/upper"
          name: go Build
