name: Artifacts
on:
  push:

defaults:
  run:
    working-directory: upper
jobs:
  capture:
    strategy:
      matrix:
        os: ['ubuntu-latest','macos-latest','windows-latest']
        
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.x'
      - run: ls
      - run: go build
      - run: ls
      - uses: actions/upload-artifact@v4
        with:
          path: "./upper/upper*"
          name: "Build ${{matrix.os}}"
